//all female wear imports
import baddieskirt from "./assets/images/database/female_Wears/baddie_skirt.jpg"
import blackjeantrousers from "./assets/images/database/female_Wears/black_jeans_trousers.jpg";
import blackleatherskirt from "./assets/images/database/female_Wears/black_leather_skirt.jpg"
import blacknikeshirt from "./assets/images/database/female_Wears/black_nike_shirt.jpg"
import blueragjean from "./assets/images/database/female_Wears/blue_rag_jean.jpg"
import creambaggytrousers from "./assets/images/database/female_Wears/cream_baggy_trousers.jpg"
import creamplaintrousers from "./assets/images/database/female_Wears/cream_plain_trousers.jpg"
import floweredsplitskirt from "./assets/images/database/female_Wears/flowered_split_skirt.jpg"
import hoodieandjoggers from "./assets/images/database/female_Wears/hoodie_and_joggers.jpg"
import indigoloosetrousers from "./assets/images/database/female_Wears/indigo_loose_trousers.jpg"
import longshirt from "./assets/images/database/female_Wears/long_shirt.jpg"
import plainformaltrousers from "./assets/images/database/female_Wears/plain_formal_trouser.jpg"
import sweatshirt from "./assets/images/database/female_Wears/SweatShirt.jpg"
import turtlenecklong from "./assets/images/database/female_Wears/turtleneck_long_skirt.jpg"
import whitejoggers from "./assets/images/database/female_Wears/white_joggers.jpg"
import femalewhiteplaintrousers from "./assets/images/database/female_Wears/female_white_plain_trousers.jpg"



export const FemaleproductsList = [

{
    "title":"Baddie Skirt",
    "image":baddieskirt,
    "id":1,
    "des":"Stripped Skirt",
    "price":"$156",
    "discount":"10%",
    "discountPrice":"$15.6",
    "rating":"",
    "qty":23,
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"High waist Black jean",
    "image":blackjeantrousers,
    "id":2,
    "des":"High waist Black Jean",
    "price":"$357",
    "discount":"8%",
    "discount Price":"28.56",
    "rating":"",
    "qty":12,
    "color":"black",
    "size":"m",
    "style":"gucci",
    "model":"long",
},
{
    "title":"Leather Crop - Black - Casual",
    "image":blackleatherskirt,
    "id":3,
    "des":"Casual Leather black outfit",
    "price":"$228",
    "discount":"10%",
    "discount Price":"$215",
    "rating":"",
    "qty":10,
    "color":"black",
    "size":"m",
    "style":"Ralph Lauren",
    "model":"short",
},
{
    "title":"Black nike SweatShirt",
    "image":blacknikeshirt,
    "id":4,
    "des":"Black nike SweatShirt",
    "price":"$344",
    "discount":"7%",
    "discount Price":"$320",
    "rating":"",
    "qty":10,
    "color":"black",
    "size":"l",
    "style":"Nike",
    "model":"Sweather",
},
{
    "title":"Blue rag jean",
    "image":blueragjean,
    "id":5,
    "des":"Blue high waist rag jean",
    "price":"$197",
    "discount":"%6",
    "discount Price":"$188",
    "rating":"",
    "qty":5,
    "color":"blue",
    "size":"m",
    "style":"Bohemian",
    "model":"Party Dresses",
},
{
    "title":"Cream colored baggy",
    "image":creambaggytrousers,
    "id":6,
    "des":"Cream colored baggy trousers",
    "price":"$190",
    "discount":"6%",
    "discount Price":"$170",
    "rating":"",
    "qty":8,
    "color":"cream",
    "size":"l",
    "style":"Casual",
    "model":"Party Dresses",
},
{
    "title":"Cream plain Trousers",
    "image":creamplaintrousers,
    "id":7,
    "des":"Formal plain Trousers",
    "price":"$480",
    "discount":"10%",
    "discount Price":"$370",
    "rating":"",
    "qty":5,
    "color":"cream",
    "size":"s",
    "style":"Business casual",
    "model":"Regular Fit",
},
{
    "title":"White plain Trousers",
    "image":femalewhiteplaintrousers,
    "id":8,
    "des":"White Formal Straight ",
    "price":"$370",
    "discount":"10%",
    "discount Price":"$322",
    "rating":"",
    "qty":18,
    "color":"white",
    "size":"m",
    "style":"Business casual",
    "model":"Regular Fit",
},
{
    "title":"Flowered Skirt",
    "image":floweredsplitskirt,
    "id":9,
    "des":"Flowered Skirt With Split",
    "price":"$300",
    "discount":"7%",
    "discount Price":"$278",
    "rating":"",
    "qty":17,
    "color":"black",
    "size":"m",
    "style":"Uniqlo",
    "model":"Party Dresses",
},
{
    "title":"Hoodie and Joggers",
    "image":hoodieandjoggers,
    "id":10,
    "des":"Stylish Joggers",
    "price":"$650",
    "discount":"10%",
    "discount Price":"$590",
    "rating":"",
    "qty":32,
    "color":"white",
    "size":"l",
    "style":"Calvin Klein",
    "model":"Sweather",
},
{
    "title":"Indigo Plain Formal Trouser",
    "image":indigoloosetrousers,
    "id":11,
    "des":"Loose Indigo formal",
    "price":"$370",
    "discount":"12%",
    "discount Price":"$322",
    "rating":"",
    "qty":10,
    "color":"indigo",
    "size":"l",
    "style":"Minimalist",
    "model":"Regular Fit",
},
{
    "title":"Checked Long Shirt",
    "image":longshirt,
    "id":12,
    "des":"Checked Long Shirt",
    "price":"$234",
    "discount":"12%",
    "discount Price":"$200",
    "rating":"",
    "qty":10,
    "color":"brown",
    "size":"xl",
    "style":"Zara",
    "model":"Sweather",
},
{
    "title":"Plain Formal Trousers",
    "image":plainformaltrousers,
    "id":13,
    "des":"White Plain Formal Wear",
    "price":"$450",
    "discount":"12%",
    "discount Price":"$422",
    "rating":"",
    "qty":6,
    "color":"white",
    "size":"s",
    "style":"Minimalist",
    "model":"Regular Fit",
},
{
    "title":"Sweat Shirt Brooklyn",
    "image":sweatshirt,
    "id":14,
    "des":"Sweat Shirt Brooklyn",
    "price":"$239",
    "discount":"10%",
    "discount Price":"$228",
    "rating":"",
    "qty":12,
    "color":"brown",
    "size":"xl",
    "style":"Mango",
    "model":"Sweather",
},
{
    "title":"Long Turtle Neck",
    "image":turtlenecklong,
    "id":15,
    "des":"White Long Turtle neck gown",
    "price":"$560",
    "discount":"11%",
    "discount Price":"$475",
    "rating":"",
    "qty":24,
    "color":"white",
    "size":"m",
    "style":"Bohemian",
    "model":"Mid-length",
},
{
    "title":"Checked blue Shirt and Joggers",
    "image":whitejoggers,
    "id":16,
    "des":"Checked blue Shirt and White Joggers",
    "price":"$390",
    "discount":"18%",
    "discount Price":"$277",
    "rating":"",
    "qty":3,
    "color":"blue",
    "size":"xl",
    "style":"Casual",
    "model":"Mid-length",
},
];



//male imports
import allblack from "./assets/images/database/male_Wears/all_black.jpg"
import baseball from "./assets/images/database/male_Wears/baseball_outfit.jpg"
import blacktrouser from "./assets/images/database/male_Wears/black_trouser.jpg"
import blueshirt from "./assets/images/database/male_Wears/blue_shirt.jpg"
import bomberjacket from "./assets/images/database/male_Wears/bomber_jacket.jpg"
import brownfromaltrouser from "./assets/images/database/male_Wears/brown_formal_trouser.jpg"
import brownjacket from "./assets/images/database/male_Wears/brown_jacket.jpg"
import brownshorts from "./assets/images/database/male_Wears/brown_shorts.jpg"
import greenpolo from "./assets/images/database/male_Wears/green_polo.jpg"
import lightgreenshirt from "./assets/images/database/male_Wears/light_green_shirt.jpg"
import lightbrownjacket from "./assets/images/database/male_Wears/lightbrown_jacket_.jpg"
import lightbrownsuit from "./assets/images/database/male_Wears/lightbrown_suit.jpg"
import looseshirt from "./assets/images/database/male_Wears/loose_shirt.jpg"
import plaintrouser from "./assets/images/database/male_Wears/plain_trouser.jpg"
import sweatshirt_lightblue from "./assets/images/database/male_Wears/sweatshirt_lightblue.jpg"
import trenchcoatbrownheavy from "./assets/images/database/male_Wears/trenchcoat_brown_heavy.jpg"
import trenchcoatwhite from "./assets/images/database/male_Wears/trenchcoat_white.jpg"
import UNIQLOcooloutfit from "./assets/images/database/male_Wears/UNIQLO_cool_outfit.jpg"
import unisexhoodie from "./assets/images/database/male_Wears/unisex_hoodie.jpg"
import vintageshirt from "./assets/images/database/male_Wears/vintage_shirt.jpg"
import whiteloosetrousers from "./assets/images/database/male_Wears/white_loose_trousers.jpg"


export const maleWearproductList = [

    {
        "title":"All black Outfit",
        "image":allblack,
        "id":17,
        "des":"Fit all black outfit",
        "price":"$390",
        "discount":"18%",
        "discount Price":"$277",
        "rating":"",
        "qty":3,
        "color":"black",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },

    {
        "title":"Baseball Outfit",
        "image":baseball,
        "id":18,
        "des":"White baseball Outfit",
        "price":"$390",
        "discount":"18%",
        "discount Price":"$277",
        "rating":"",
        "qty":3,
        "color":"white",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"black trouser",
        "image":blacktrouser,
        "id":19,
        "des":"black Trouser",
        "price":"$490",
        "discount":"18%",
        "discount Price":"$277",
        "rating":"",
        "qty":3,
        "color":"black",
        "size":"l",
        "style":"Casual",
        "model":"Regular Fit",
    },
    {
        "title":"blue Shirt",
        "image":blueshirt,
        "id":20,
        "des":"pale blue shirt",
        "price":"$590",
        "discount":"18%",
        "discount Price":"$247",
        "rating":"",
        "qty":3,
        "color":"blue",
        "size":"s",
        "style":"Casual",
        "model":"Regular Fit",
    },
    {
        "title":"bomber jacket",
        "image":bomberjacket,
        "id":21,
        "des":"bomber jacket",
        "price":"$590",
        "discount":"12%",
        "discount Price":"$577",
        "rating":"",
        "qty":3,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"brown formal trouser",
        "image":brownfromaltrouser,
        "id":22,
        "des":"Brown formal trouser",
        "price":"$290",
        "discount":"11%",
        "discount Price":"$577",
        "rating":"",
        "qty":3,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"brown jacket",
        "image":brownjacket,
        "id":23,
        "des":"brown jacket",
        "price":"$160",
        "discount":"13%",
        "discount Price":"$397",
        "rating":"",
        "qty":3,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"brown shorts",
        "image":brownshorts,
        "id":24,
        "des":"brown shorts",
        "price":"$280",
        "discount":"12%",
        "discount Price":"$344",
        "rating":"",
        "qty":3,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"green polo",
        "image":greenpolo,
        "id":25,
        "des":"green polo for guys",
        "price":"$399",
        "discount":"4%",
        "discount Price":"$290",
        "rating":"",
        "qty":3,
        "color":"green",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"light green shirt",
        "image":lightgreenshirt,
        "id":26,
        "des":"light green shirt",
        "price":"$90",
        "discount":"4%",
        "discount Price":"$79",
        "rating":"",
        "qty":7,
        "color":"green",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"light brown jacket",
        "image":lightbrownjacket,
        "id":27,
        "des":"light brown jacket",
        "price":"$700",
        "discount":"14%",
        "discount Price":"$697",
        "rating":"",
        "qty":9,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"light brown suit",
        "image":lightbrownsuit,
        "id":28,
        "des":"light brown suit",
        "price":"$290",
        "discount":"11%",
        "discount Price":"$188",
        "rating":"",
        "qty":3,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"loose shirt",
        "image":looseshirt,
        "id":29,
        "des":"loose mens wear shirt",
        "price":"$200",
        "discount":"11%",
        "discount Price":"$188",
        "rating":"",
        "qty":3,
        "color":"white",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"plain trouser",
        "image":plaintrouser,
        "id":30,
        "des":"white plain trouser",
        "price":"$400",
        "discount":"11%",
        "discount Price":"$344",
        "rating":"",
        "qty":7,
        "color":"white",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"sweatshirt light blue",
        "image":sweatshirt_lightblue,
        "id":31,
        "des":"sweat shirt light blue",
        "price":"$400",
        "discount":"11%",
        "discount Price":"$337",
        "rating":"",
        "qty":8,
        "color":"blue",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"trench coat",
        "image":trenchcoatbrownheavy,
        "id":32,
        "des":"trench coat brown heavy",
        "price":"$780",
        "discount":"16%",
        "discount Price":"$666",
        "rating":"",
        "qty":8,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"trench coat white",
        "image":trenchcoatwhite,
        "id":33,
        "des":"trench coat white",
        "price":"$290",
        "discount":"13%",
        "discount Price":"$277",
        "rating":"",
        "qty":8,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"uniqlo outfit",
        "image":UNIQLOcooloutfit,
        "id":34,
        "des":"uniqlo cool outfit",
        "price":"$580",
        "discount":"13%",
        "discount Price":"$557",
        "rating":"",
        "qty":7,
        "color":"green",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"unisex hoodie",
        "image":unisexhoodie,
        "id":35,
        "des":"unisex hoodie",
        "price":"$160",
        "discount":"10%",
        "discount Price":"$144",
        "rating":"",
        "qty":7,
        "color":"brown",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"vintage shirt",
        "image":vintageshirt,
        "id":36,
        "des":"vintage shirt white",
        "price":"$470",
        "discount":"14%",
        "discount Price":"$390",
        "rating":"",
        "qty":9,
        "color":"white",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    {
        "title":"white loose trouser",
        "image":whiteloosetrousers,
        "id":37,
        "des":"Fit all black outfit",
        "price":"$1800",
        "discount":"7%",
        "discount Price":"$887",
        "rating":"",
        "qty":7,
        "color":"white",
        "size":"m",
        "style":"Casual",
        "model":"Mid-length",
    },
    
]