//all female wear imports
import baddieskirt from "./assets/images/database/female_Wears/baddie_skirt.jpg"
import blackjeantrousers from "./assets/images/database/female_Wears/black_jeans_trousers.jpg";
import blackleatherskirt from "./assets/images/database/female_Wears/black_leather_skirt.jpg"
import blacknikeshirt from "./assets/images/database/female_Wears/black_nike_shirt.jpg"
import blueragjean from "./assets/images/database/female_Wears/blue_rag_jean.jpg"
import creambaggytrousers from "./assets/images/database/female_Wears/cream_baggy_trousers.jpg"
import creamplaintrousers from "./assets/images/database/female_Wears/cream_plain_trousers.jpg"
import floweredsplitskirt from "./assets/images/database/female_Wears/flowered_split_skirt.jpg"
import hoodieandjoggers from "./assets/images/database/female_Wears/hoodie_and_joggers.jpg"
import indigoloosetrousers from "./assets/images/database/female_Wears/indigo_loose_trousers.jpg"
import longshirt from "./assets/images/database/female_Wears/long_shirt.jpg"
import plainformaltrousers from "./assets/images/database/female_Wears/plain_formal_trouser.jpg"
import sweatshirt from "./assets/images/database/female_Wears/SweatShirt.jpg"
import turtlenecklong from "./assets/images/database/female_Wears/turtleneck_long_skirt.jpg"
import whitejoggers from "./assets/images/database/female_Wears/white_joggers.jpg"
import femalewhiteplaintrousers from "./assets/images/database/female_Wears/female_white_plain_trousers.jpg"



export const FemaleproductsList = [

{
    "title":"",
    "image":baddieskirt,
    "id":1,
    "des":"",
    "price":"$243",
    "discount":"",
    "discountPrice":"",
    "rating":"",
    "qty":23,
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":blackjeantrousers,
    "id":2,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":blackleatherskirt,
    "id":3,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":blacknikeshirt,
    "id":4,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":blueragjean,
    "id":5,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":creambaggytrousers,
    "id":6,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":creamplaintrousers,
    "id":7,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":"",
    "id":8,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":femalewhiteplaintrousers,
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":floweredsplitskirt,
    "id":9,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":hoodieandjoggers,
    "id":10,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":indigoloosetrousers,
    "id":11,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":longshirt,
    "id":12,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":plainformaltrousers,
    "id":13,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":sweatshirt,
    "id":14,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":turtlenecklong,
    "id":15,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"",
    "image":whitejoggers,
    "id":16,
    "des":"",
    "price":"$234",
    "discount":"",
    "discount Price":"",
    "rating":"",
    "qty":"23",
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
];


export const maleWearproductList = [



]