//all female wear imports
import baddieskirt from "./assets/images/database/female_Wears/baddie_skirt.jpg"
import blackjeantrousers from "./assets/images/database/female_Wears/black_jeans_trousers.jpg";
import blackleatherskirt from "./assets/images/database/female_Wears/black_leather_skirt.jpg"
import blacknikeshirt from "./assets/images/database/female_Wears/black_nike_shirt.jpg"
import blueragjean from "./assets/images/database/female_Wears/blue_rag_jean.jpg"
import creambaggytrousers from "./assets/images/database/female_Wears/cream_baggy_trousers.jpg"
import creamplaintrousers from "./assets/images/database/female_Wears/cream_plain_trousers.jpg"
import floweredsplitskirt from "./assets/images/database/female_Wears/flowered_split_skirt.jpg"
import hoodieandjoggers from "./assets/images/database/female_Wears/hoodie_and_joggers.jpg"
import indigoloosetrousers from "./assets/images/database/female_Wears/indigo_loose_trousers.jpg"
import longshirt from "./assets/images/database/female_Wears/long_shirt.jpg"
import plainformaltrousers from "./assets/images/database/female_Wears/plain_formal_trouser.jpg"
import sweatshirt from "./assets/images/database/female_Wears/SweatShirt.jpg"
import turtlenecklong from "./assets/images/database/female_Wears/turtleneck_long_skirt.jpg"
import whitejoggers from "./assets/images/database/female_Wears/white_joggers.jpg"
import femalewhiteplaintrousers from "./assets/images/database/female_Wears/female_white_plain_trousers.jpg"



export const FemaleproductsList = [

{
    "title":"Baddie Skirt",
    "image":baddieskirt,
    "id":1,
    "des":"Stripped Skirt",
    "price":"$156",
    "discount":"10%",
    "discountPrice":"$15.6",
    "rating":"",
    "qty":23,
    "color":"black",
    "size":"s",
    "style":"gucci",
    "model":"short",
},
{
    "title":"High waist Black jean",
    "image":blackjeantrousers,
    "id":2,
    "des":"High waist Black Jean",
    "price":"$357",
    "discount":"8%",
    "discount Price":"28.56",
    "rating":"",
    "qty":12,
    "color":"black",
    "size":"m",
    "style":"gucci",
    "model":"long",
},
{
    "title":"Leather Crop - Black - Casual",
    "image":blackleatherskirt,
    "id":3,
    "des":"Casual Leather black outfit",
    "price":"$228",
    "discount":"10%",
    "discount Price":"$215",
    "rating":"",
    "qty":10,
    "color":"black",
    "size":"m",
    "style":"Ralph Lauren",
    "model":"short",
},
{
    "title":"Black nike SweatShirt",
    "image":blacknikeshirt,
    "id":4,
    "des":"Black nike SweatShirt",
    "price":"$344",
    "discount":"7%",
    "discount Price":"$320",
    "rating":"",
    "qty":10,
    "color":"black",
    "size":"l",
    "style":"Nike",
    "model":"Sweather",
},
{
    "title":"Blue rag jean",
    "image":blueragjean,
    "id":5,
    "des":"Blue high waist rag jean",
    "price":"$197",
    "discount":"%6",
    "discount Price":"$188",
    "rating":"",
    "qty":5,
    "color":"blue",
    "size":"m",
    "style":"Bohemian",
    "model":"Party Dresses",
},
{
    "title":"Cream colored baggy",
    "image":creambaggytrousers,
    "id":6,
    "des":"Cream colored baggy trousers",
    "price":"$190",
    "discount":"6%",
    "discount Price":"$170",
    "rating":"",
    "qty":8,
    "color":"cream",
    "size":"l",
    "style":"Casual",
    "model":"Party Dresses",
},
{
    "title":"Cream plain Trousers",
    "image":creamplaintrousers,
    "id":7,
    "des":"Formal plain Trousers",
    "price":"$480",
    "discount":"10%",
    "discount Price":"$370",
    "rating":"",
    "qty":5,
    "color":"cream",
    "size":"s",
    "style":"Business casual",
    "model":"Regular Fit",
},
{
    "title":"White plain Trousers",
    "image":femalewhiteplaintrousers,
    "id":8,
    "des":"White Formal Straight ",
    "price":"$370",
    "discount":"10%",
    "discount Price":"$322",
    "rating":"",
    "qty":18,
    "color":"white",
    "size":"m",
    "style":"Business casual",
    "model":"Regular Fit",
},
{
    "title":"Flowered Skirt",
    "image":floweredsplitskirt,
    "id":9,
    "des":"Flowered Skirt With Split",
    "price":"$300",
    "discount":"7%",
    "discount Price":"$278",
    "rating":"",
    "qty":17,
    "color":"black",
    "size":"m",
    "style":"Uniqlo",
    "model":"Party Dresses",
},
{
    "title":"Hoodie and Joggers",
    "image":hoodieandjoggers,
    "id":10,
    "des":"Stylish Joggers",
    "price":"$650",
    "discount":"10%",
    "discount Price":"$590",
    "rating":"",
    "qty":32,
    "color":"white",
    "size":"l",
    "style":"Calvin Klein",
    "model":"Sweather",
},
{
    "title":"Indigo Plain Formal Trouser",
    "image":indigoloosetrousers,
    "id":11,
    "des":"Loose Indigo formal",
    "price":"$370",
    "discount":"12%",
    "discount Price":"$322",
    "rating":"",
    "qty":10,
    "color":"indigo",
    "size":"l",
    "style":"Minimalist",
    "model":"Regular Fit",
},
{
    "title":"Checked Long Shirt",
    "image":longshirt,
    "id":12,
    "des":"Checked Long Shirt",
    "price":"$234",
    "discount":"12%",
    "discount Price":"$200",
    "rating":"",
    "qty":10,
    "color":"brown",
    "size":"xl",
    "style":"Zara",
    "model":"Sweather",
},
{
    "title":"Plain Formal Trousers",
    "image":plainformaltrousers,
    "id":13,
    "des":"White Plain Formal Wear",
    "price":"$450",
    "discount":"12%",
    "discount Price":"$422",
    "rating":"",
    "qty":6,
    "color":"white",
    "size":"s",
    "style":"Minimalist",
    "model":"Regular Fit",
},
{
    "title":"Sweat Shirt Brooklyn",
    "image":sweatshirt,
    "id":14,
    "des":"Sweat Shirt Brooklyn",
    "price":"$239",
    "discount":"10%",
    "discount Price":"$228",
    "rating":"",
    "qty":12,
    "color":"brown",
    "size":"xl",
    "style":"Mango",
    "model":"Sweather",
},
{
    "title":"Long Turtle Neck",
    "image":turtlenecklong,
    "id":15,
    "des":"White Long Turtle neck gown",
    "price":"$560",
    "discount":"11%",
    "discount Price":"$475",
    "rating":"",
    "qty":24,
    "color":"white",
    "size":"m",
    "style":"Bohemian",
    "model":"Mid-length",
},
{
    "title":"Checked blue Shirt and Joggers",
    "image":whitejoggers,
    "id":16,
    "des":"Checked blue Shirt and White Joggers",
    "price":"$390",
    "discount":"18%",
    "discount Price":"$277",
    "rating":"",
    "qty":3,
    "color":"blue",
    "size":"xl",
    "style":"Casual",
    "model":"Mid-length",
},
];


export const maleWearproductList = [



]